import numpy
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.read_csv("data.csv", header=0, delimiter=";")
df["c/n"] = df["cmps"]/df["n"]
df["s/n"] = df["swaps"]/df["n"]
sns.set_style("darkgrid")

plt.title("insertion cmps")
sns.lineplot(data=df[df.type == 'insertion'], x='n', y = 'cmps')
plt.savefig('plots/insertion_cmps.png')
plt.clf()
plt.title("merge cmps")
sns.lineplot(data=df[df.type == 'merge'], x='n', y = 'cmps')
plt.savefig('plots/merge_cmps.png')
plt.clf()
plt.title("quick_sort cmps")
sns.lineplot(data=df[df.type == 'quick'], x='n', y = 'cmps')
plt.savefig('plots/quick_sort_cmps.png')
plt.clf()
plt.title("dp_quick_sort cmps")
sns.lineplot(data=df[df.type == 'dp_quick'], x='n', y = 'cmps')
plt.savefig('plots/dp_quick_sort_cmps.png')
plt.clf()

plt.title("insertion swaps")
sns.lineplot(data=df[df.type == 'insertion'], x='n', y = 'swaps')
plt.savefig('plots/insertion_swaps.png')
plt.clf()
plt.title("merge swaps")
sns.lineplot(data=df[df.type == 'merge'], x='n', y = 'swaps')
plt.savefig('plots/merge_swaps.png')
plt.clf()
plt.title("quick_sort swaps")
sns.lineplot(data=df[df.type == 'quick'], x='n', y = 'swaps')
plt.savefig('plots/quick_sort_swaps.png')
plt.clf()
plt.title("dp_quick_sort swaps")
sns.lineplot(data=df[df.type == 'dp_quick'], x='n', y = 'swaps')
plt.savefig('plots/dp_quick_sort_swaps.png')
plt.clf()

plt.title("insertion c/n")
sns.lineplot(data=df[df.type == 'insertion'], x='n', y = "c/n")
plt.savefig('plots/insertion_cn.png')
plt.clf()
plt.title("merge c/n")
sns.lineplot(data=df[df.type == 'merge'], x='n', y = 'c/n')
plt.savefig('plots/merge_cn.png')
plt.clf()
plt.title("quick_sort c/n")
sns.lineplot(data=df[df.type == 'quick'], x='n', y = 'c/n')
plt.savefig('plots/quick_sort_cn.png')
plt.clf()
plt.title("dp_quick_sort c/n")
sns.lineplot(data=df[df.type == 'dp_quick'], x='n', y = 'c/n')
plt.savefig('plots/dp_quick_sort_cn.png')
plt.clf()

plt.title("insertion s/n")
sns.lineplot(data=df[df.type == 'insertion'], x='n', y = "s/n")
plt.savefig('plots/insertion_sn.png')
plt.clf()
plt.title("merge s/n")
sns.lineplot(data=df[df.type == 'merge'], x='n', y = 's/n')
plt.savefig('plots/merge_sn.png')
plt.clf()
plt.title("quick_sort s/n")
sns.lineplot(data=df[df.type == 'quick'], x='n', y = 's/n')
plt.savefig('plots/quick_sort_sn.png')
plt.clf()
plt.title("dp_quick_sort s/n")
sns.lineplot(data=df[df.type == 'dp_quick'], x='n', y = 's/n')
plt.savefig('plots/dp_quick_sort_sn.png')
plt.clf()

df = df[(df['type'] == 'quick' ) | (df['type'] == 'dp_quick')]
plt.title("quick_sort comp cmps")
sns.lineplot(data=df, x='n', y = 'cmps', hue='type')
plt.savefig('plots/quick_sort_comp_cmps.png')
plt.clf()
plt.title("quick_sort comp cmps")
sns.lineplot(data=df, x='n', y = 'swaps', hue='type')
plt.savefig('plots/quick_sort_comp_swaps.png')
plt.clf()
plt.title("quick_sort comp c/n")
sns.lineplot(data=df, x='n', y = 'c/n', hue='type')
plt.savefig('plots/quick_sort_comp_cn.png')
plt.clf()
plt.title("quick_sort comp s/n")
sns.lineplot(data=df, x='n', y = 's/n', hue='type')
plt.savefig('plots/quick_sort_comp_sn.png')
plt.clf()
